### PR TITLE
Add dependency on bundler-stats and improve output

### PR DESCRIPTION
**Pull request by etagwerker**
Hey,

This PR fixes https://github.com/fastruby/rails_stats/issues/11 by adding a dependency to `bundler-stats` and including a call to its CLI. 

Please check it out.

Thanks!

### CODE REVIEW

**Comment by kindoflew** [comment]
hi @torresga! could you please review this PR? thanks!

**Review by torresga — APPROVED** [review]

**Comment by torresga** [comment]
@kindoflew Hey I took a look at the PR - I did notice some of the tests are failing though - is that supposed to be happening? Should we take a look at that more in detail?

**Comment by kindoflew** [comment]
@torresga, thanks! it probably isn't, but while I was busy trying to follow the stack trace, it seems @etagwerker was already working on a solution and opened a PR elsewhere to fix it 😅 .

**Comment by etagwerker** [comment]
Looking into it. It seems to be a very specific issue related to bundler stats and github CI.

**Comment by kindoflew** [comment]
Since [bundler-stats/#19](https://github.com/jmmastey/bundler-stats/pull/19) is merged, can the new version be added yet or do we have to wait for a new release?

**Comment by etagwerker** [comment]
@kindoflew I just updated my changes to work with the latest version of bundler-stats... 

I see that there are still a couple of failed jobs. I'll look into this now.

**Comment by etagwerker** [comment]
@kindoflew @torresga I finally got a passing test suite + codecov job! 

I had to tweak the tests to increase code coverage (because Codecov was complaining about diminishing test coverage percentage) and I had to add a different expectation for the Ruby 2.4 job (apparently number of dependencies is different for that version of Ruby) 

Please take another look and let me know what you think. Thanks!

**Comment by kindoflew** [comment]
Looks good to me!

**Review by kindoflew — APPROVED** [review]

**Pull request merged**
