### PR TITLE
Start running test suite with GitHub actions and reporting coverage to Codecov

### PR DESCRIPTION
**Pull request by etagwerker**
Hi there,

This is an attempt to run the test suite on every PR and report code coverage metrics to Codecov. 

Please check it out. 

Thanks!

### CODE REVIEW

**Comment by lubc** [comment]
@rdormer hey, could you review this PR when you have some time? Thanks!

**Review by rdormer — APPROVED** [review]

**Comment by bronzdoc** [comment]
@etagwerker it is expected that the test suite fails in all rubies?

**Comment by etagwerker** [comment]
@bronzdoc Weird, that is unexpected. I'll look into it.

**Comment by etagwerker** [comment]
@lubc @bronzdoc Closing this in favor of https://github.com/fastruby/rails_stats/pull/18

**Pull request closed without merging**
